fragment PageParts on Page {
  __typename
  title
  description
  hideTitleAndDescription
  blocks {
    __typename
    ... on PageBlocksContent {
      content
    }
    ... on PageBlocksBrandSlogan {
      title
      slogan
      illustrationSvg
    }
    ... on PageBlocksNavCards {
      cards {
        __typename
        title
        description
        link
      }
    }
  }
}

fragment ComponentParts on Component {
  __typename
  title
  subtitle
  body
}

fragment GlobalParts on Global {
  __typename
  header {
    __typename
    shortHeader
    nav {
      __typename
      href
      label
      external
      iconSvg
      iconBehaviour
    }
  }
}
