fragment PostParts on Post {
  __typename
  title
  subtitle
  body
}

fragment GlobalParts on Global {
  __typename
  header {
    __typename
    nav {
      __typename
      href
      label
      external
      iconSvg
      iconBehaviour
    }
  }
}
