version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: auto
    groups:
      minor-and-patch:
        update-types:
        - "minor"
        - "patch"