export const PostenColorsSignatureRed : "#e32d22";
export const PostenColorsDarkerRed : "#4a1011";
export const PostenColorsDarkRed : "#980000";
export const PostenColorsLightRed : "#ff8a5f";
export const PostenColorsLighterRed : "#fff5f0";
export const PostenColorsSignatureRedHover : "#d62722";
export const PostenColorsLightRedHover : "#ff7d55";
export const BringColorsSignatureGreen : "#7bc144";
export const BringColorsDarkerGreen : "#002f19";
export const BringColorsDarkGreen : "#00643a";
export const BringColorsLightGreen : "#c8dc8c";
export const BringColorsLighterGreen : "#f1f7e9";
export const BringColorsSignatureGreenHover : "#86cc4a";
export const BringColorsLightGreenHover : "#d3e593";
export const UiColorsBlack : "#000000";
export const UiColorsDarkGrey : "#6e6e6e";
export const UiColorsGrey : "#d6d6d6";
export const UiColorsLightGreyStroke : "#e4e4e4";
export const UiColorsLightGreyFill : "#f2f2f2";
export const UiColorsWhite : "#ffffff";
export const UiColorsWarningYellow : "#fdbb2f";
export const UiColorsWarningYellowStroke : "#d68000";
export const UiColorsWarningYellowLightFill : "#fff5e0";
export const UiColorsWarningYellowHover : "#ffc340";
export const UiColorsBlackHover : "#1e1e1e";
/** Base color for dark mode */
export const DarkModeColorsObsidian : "#121212";
/** Background on none-clickable cards */
export const DarkModeColorsCoal : "#252525";
/** Fill inputfields, checkbox, radiobuttons, toogles */
export const DarkModeColorsDusk : "#2c2c2c";
/** Clickable cards or tiles */
export const DarkModeColorsSpider : "#333333";
/** Default radio buttons, checkbox, label on inputsfields, toogle off  (background) */
export const DarkModeColorsAsh : "#999999";
export const SpacingSmall1 : "4px";
export const SpacingSmall2 : "8px";
export const SpacingSmall3 : "12px";
export const SpacingSmall4 : "16px";
export const SpacingMedium1 : "20px";
export const SpacingMedium2 : "24px";
export const SpacingMedium3 : "32px";
export const SpacingMedium4 : "40px";
export const SpacingLarge1 : "48px";
export const SpacingLarge2 : "64px";
export const SpacingLarge3 : "80px";
export const SpacingLarge4 : "120px";
export const SpacingLarge5 : "160px";
export const FontsPostenSansBold : string[];
export const FontsPostenSansMedium : string[];
export const FontsPostenSansRegular : string[];
export const FontsPostenSansLight : string[];
export const TypographyPostenH1Display : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyPostenH1 : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyPostenH2 : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyBringH1Display : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyBringH1 : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyBringH2 : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyHeaderH3 : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyHeaderH3Title : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyBody : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyBodyTitle : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyBodySmall : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyBodySmallTitle : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyTechnical : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyTechnicalTitle : { fontFamily: string[], fontSize: string[], lineHeight: string[], fontWeight: number, letterSpacing: string };
export const TypographyCaption : { fontFamily: string[], fontSize: string, lineHeight: string, fontWeight: number, letterSpacing: string };
export const TypographyCaptionTitle : { fontFamily: string[], fontSize: string, lineHeight: string, fontWeight: number, letterSpacing: string };
export const BorderRadius : "2px";
export const StrokeDefault : "1px";
export const StrokeThick : "2px";
export const ShadowDefault : { color: string, offsetX: string, offsetY: string, blur: string, spread: string };
export const MicroAnimationEasingIn : number[];
export const MicroAnimationEasingOut : number[];
export const MicroAnimationEasingNormal : number[];
export const MicroAnimationDurationQuick : "0.130s";
export const MicroAnimationDurationNormal : "0.300s";
export const MicroAnimationDurationSlow : "0.700s";
export const BreakpointsSmall : "460px";
export const BreakpointsMedium : "720px";
export const BreakpointsLarge : "940px";
export const BreakpointsXlarge : "1200px";
export const Opacity7 : ".07";
export const Opacity10 : ".1";
export const Opacity20 : ".2";
export const Opacity50 : ".5";
