/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    fontFamily: {
      bold: "var(--hds-fonts-posten-sans-bold)",
      medium: "var(--hds-fonts-posten-sans-medium)",
      regular: "var(--hds-fonts-posten-sans-regular)",
      light: "var(--hds-fonts-posten-sans-light)",
    },
    fontSize: {
      /* minimum font sizes */
      body: ["18px", "26px"],
      "body-small": ["16px", "24px"],
      technical: ["14px", "22px"],
      caption: ["13px", "18px"],
      h3: ["22px", "28px"],
      h2: ["28px", "36px"],
      h1: ["32px", "40px"],
      "h1-display": ["40px", "56px"],
      /* maximum font sizes */
      "body-max": ["20px", "28px"],
      "body-small-max": ["18px", "26px"],
      "technical-max": ["16px", "24px"],
      "h3-max": ["24px", "32px"],
      "h2-max": ["32px", "40px"],
      "h1-max": ["48px", "56px"],
      "h1-display-max": ["72px", "80px"],
    },
    colors: {
      signature: "var(--hds-brand-colors-signature)",
      darker: "var(--hds-brand-colors-darker)",
      dark: "var(--hds-brand-colors-dark)",
      light: "var(--hds-brand-colors-light)",
      lighter: "var(--hds-brand-colors-lighter)",
      "signature-hover": "var(--hds-brand-colors-signature-hover)",
      "light-hover": "var(--hds-brand-colors-light-hover)",

      "ui-black": "var(--hds-ui-colors-black)",
      "ui-dark-grey": "var(--hds-ui-colors-dark-grey)",
      "ui-grey": "var(--hds-ui-colors-grey)",
      "ui-light-grey-stroke": "var(--hds-ui-colors-light-grey-stroke)",
      "ui-light-grey-fill": "var(--hds-ui-colors-light-grey-fill)",
      "ui-white": "var(--hds-ui-colors-white)",
      "ui-warning-yellow": "var(--hds-ui-colors-warning-yellow)",
      "ui-warning-yellow-stroke": "var(--hds-ui-colors-warning-yellow-stroke)",
      "ui-warning-yellow-light-fill": "var(--hds-ui-colors-warning-yellow-light-fill)",
      "ui-warning-yellow-hover": "var(--hds-ui-colors-warning-yellow-hover)",
      "ui-black-hover": "var(--hds-ui-colors-black-hover)",

      "dm-obsidian": "var(--hds-dark-mode-colors-obsidian)",
      "dm-coal": "var(--hds-dark-mode-colors-coal)",
      "dm-dusk": "var(--hds-dark-mode-colors-dusk)",
      "dm-spider": "var(--hds-dark-mode-colors-spider)",
      "dm-ash": "var(--hds-dark-mode-colors-ash)",
    },
    spacing: {
      0: 0,
      "small-1": "var(--hds-spacing-small-1)",
      "small-2": "var(--hds-spacing-small-2)",
      "small-3": "var(--hds-spacing-small-3)",
      "small-4": "var(--hds-spacing-small-4)",
      "medium-1": "var(--hds-spacing-medium-1)",
      DEFAULT: "var(--hds-spacing-medium-2)",
      "medium-2": "var(--hds-spacing-medium-2)",
      "medium-3": "var(--hds-spacing-medium-3)",
      "medium-4": "var(--hds-spacing-medium-4)",
      "large-1": "var(--hds-spacing-large-1)",
      "large-2": "var(--hds-spacing-large-2)",
      "large-3": "var(--hds-spacing-large-3)",
      "large-4": "var(--hds-spacing-large-4)",
      "large-5": "var(--hds-spacing-large-5)",
    },
    listStyleType: {
      none: "none",
      DEFAULT: "disc",
    },
    borderStyle: {
      DEFAULT: "solid",
    },
    borderRadius: {
      0: 0,
      DEFAULT: "var(--hds-border-radius)",
    },
    borderWidth: {
      0: 0,
      DEFAULT: "var(--hds-stroke-default)",
      2: "var(--hds-stroke-thick)",
    },
    boxShadow: {
      "card-hover": "0 1px 3px 0 rgb(0 0 0 / 12%)",
    },
    screens: {
      small: "var(--hds-breakpoints-small)",
      medium: "var(--hds-breakpoints-medium)",
      large: "var(--hds-breakpoints-large)",
      xlarge: "var(--hds-breakpoints-xlarge)",
    },
    opacity: {
      0: 0,
      7: "var(--hds-opacity-7)",
      10: "var(--hds-opacity-10)",
      20: "var(--hds-opacity-20)",
      50: "var(--hds-opacity-50)",
    },
    extend: {},
  },
  corePlugins: {
    fontWeight: false,
    ringColor: false,
    ringOffsetColor: false,
    ringOffsetWidth: false,
    ringOpacity: false,
    ringWidth: false,
    borderStyle: false,
    divideWidth: false,
    divideColor: false,
    divideOpacity: false,
    divideStyle: false,
    borderOpacity: false,
  },
};
