name: Release Snapshot Version

on:
  push:
    branches-ignore:
      - master
      - changeset-release/*

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-snapshot:
    name: Release Snapshot Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Set snapshot version
        run: pnpm dlx changeset version --snapshot ${GITHUB_REF##*/}

      - name: Setup .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> $HOME/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish snapshot versions to npm
        run: pnpm dlx turbo run build --filter=docs^... && pnpm dlx changeset publish --no-git-tag --tag ${GITHUB_REF##*/}
