name: Release Snapshot Version

on:
  push:
    branches-ignore:
      - master
      - changeset-release/*
      - dependabot/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-snapshot:
    name: Release Snapshot Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Set and publish snapshot versions to npm registry
        run: |
          SANITIZED_REF=$(echo ${GITHUB_REF##*/} | sed 's/[^0-9a-z.-]/-/g')
          pnpm changeset version --snapshot $SANITIZED_REF
          pnpm turbo run build --filter=docs^... && pnpm changeset publish --no-git-tag --tag $SANITIZED_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
